version: '3.9'

services:
  django:
    build:
      context: .
      dockerfile: './backend/Dockerfile'
    image: image_app_django
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    command: sh ./init.sh

  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - image_app_postgres_data:/var/lib/postgresql/data

  react:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  image_app_postgres_data: {}